version: '3'
services:
  app:
    container_name: aiotechz-demo
    image: 35.198.238.199:8082/cyl3erpunkz/aiotechz-demo:latest
    restart: always
    expose:
      - 8080
  nginx:
    container_name: reverse-proxy
    image: nginx:1.17
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
